### ISSUE TITLE
Equipment as a parent table?

### ISSUE THREAD

**Issue by ernogispo** [ORGTYTESPOO/kiradigiasm#10]
Currently equipment is a separate table though, for example TrafficSign, TrafficSignMounting and some other tables are equipment tables. Also, many equipment types do not currently have own table. Maybe it is fine that not all equipment types have own table but maybe those that have should inherit the Equipment table.

Also, for reporting to be efficient, the equipment table(s) should have link to InfraPart table. This can be done by adding the foreign key to the Equipment table that is then inherited by child tables.

**Comment by Tapir79** [comment]
Actually I was thinking about the same thing yesterday and I listed all the equipment tables that should be child tables of the Equipment table!
I'll make issues of all of the different tables!
