### ISSUE TITLE
change signtype smallint in table TrafficSign to character varying

### ISSUE THREAD

**Issue by Tapir79** [ORGTYTESPOO/kiradigiasm#2]
signtype smallint can't be **integer** since codes can be
"181"
"644"
"231"
"363_20"
"152"
"521"
"423"
"852"
"562"
"824"
"361_100"
"574"
"826"
"643"
"844"
"414"
"421"
"812"
"372"
"Unclassified"
"413"
"161"
"651"
"611"
"683"
"324"
"828"
"645"
"412"
"704a"
"872"
"521a"
"851"
"841"
"362_30"
"681"
"323"
"677"
"312"
"141a"
"322"
"374"
"361_30"
"521b"
"854"
"114"
"361_60"
"871"
"347"
"364_30"
"427"
"623"
"121"
"417"
"142"
"411"
"836"
"814"
"662"
"361_40"
"422"
"361_10"
"832"
"425"
"363_30"
"232"
"311"
"522"
"822"
"361_20"
"416"
"332"
"333"
"816"
"189"
"371"
"621"
"682"
"112"
"551"
"343"
"843"
"521c"
"532"
"704"
"331"
"151"
"342"
"834"
"571"
"845"
"534"
"313"
"827"
"361_50"
"573"
"677a"
"141"
"813"
"418"
"856b"
"363_40"
"165"
"373"
"511"
"649"
"531"
"424"
"815"
"364_40"
"701"
"652"
"122"
"842"
"641"
"375"
"376"
"648"
"132"
"685"
"147"
"863"
"831"
"361_5"
"344"
"566"
"811"
"821"

**Comment by posikifi** [comment]
Hi,
It seems all those signs with "_" underscore are speed limits traffic signs, according Liikennevirasto ( http://www.liikennevirasto.fi/tieverkko/liikennemerkit/kielto-ja-rajoitusmerkit)

- 361 Speed limit => 361_30 Speed limit 30 km/h (?)
- 362 End of speed limit
- 363 Speed limit area
- 364 End of speed limit area

Traffic signs with letter

521 Parking area
677 Parking area

8xx are extra sign plates ("Lisäkilvet")
856 Pysäköintikiekon käyttövelvollisuus..

I think this still should be smallinteger.

**Comment by ernoma** [comment]
Hi,

A moment ago I made pull request #3 where the signtype is varchar. Maybe it is ok if you @posikifi review the the pull request and do the changes you still think need to be done before @Tapir79 merges the request?

**Comment by Tapir79** [comment]
@posikifi Agreed! :) We'll filter the data through a few rules and make it numbers then. Speed limit underscore can be removed since no other sign has the same base code. @posikifi @ernoma won't merge yet. Let me know when you are done!
