### ISSUE TITLE
Add  Mounting - Equipment child table

### ISSUE THREAD

**Issue by Tapir79** [ORGTYTESPOO/kiradigiasm#22]
attributes: type (traffic sign mounting, streetlight pole, traffic light mounting)
link: TrafficSign, StreetLight, TrafficLight

@ernogispo do you agree with this or have a better solution?

**Comment by ernogispo** [comment]
@Tapir79 I agree with this.

**Comment by Tapir79** [comment]
So TrafficSignMounting and LightPole tables should be removed and the new table named to Mounting?

**Comment by ernogispo** [comment]
Mounting table could have enumeration for those removed tables (and for traffic sign mounting).
