### ISSUE TITLE
Add MaintenanceArea - table

### ISSUE THREAD

**Issue by Tapir79** [ORGTYTESPOO/kiradigiasm#6]
Based on comments in the latest workshop MaintenanceAreas should have their own table with own geometry. 
Attributes: MaintenanceClass
Link: MaintenaceCard

Question: Should inherit from InfraPart?

**Comment by ernogispo** [comment]
How this is different from the MaintenanceRegion? Currently one MaintenanceRegion can have several assets (such as equipment) and each asset has the MaintenanceClass attribute. So, currently  MaintenanceRegion does not have it's own MaintenanceClass. Would it be enough to add MaintenanceClass as attribute to the MaintenanceRegion to do this enhancement?

**Comment by ernogispo** [comment]
Since MaintenanceClass is changed to MaintenanceCard based on decision mentioned in the Kakedigi blog (https://kakedigi.wordpress.com/2017/07/06/omaisuudenhallinnan-tietosisallon-tyopajoja/), I guess it is still ok to have separate MaintenanceCard for each asset.

**Comment by Tapir79** [comment]
This was a long discussion that went on for several hours and there's probably no right answer to this. 
This would be similar to RoadLayer. Each road/green area have their own polygon that is then divided into several smaller polygons according to the maintenance class. 
 MaintenanceRegion does not hold geometry and the idea was that maintenanceclass areas, wintermaintenance areas, bridges, underpasses etc. should all have separate areas that are updated separately and also if the larger assetarea changes. 

My original idea for the AreaRegion -table was to add all kinds of area outlines for map making. So they would be like cookie cutters for the data. Each region would hold a geometry and type to know what kind of map it was used for. 
With these regions we could automatically generate hardcoded data that would change overnight if any region changes. The hardcoded data could be in the MaintenanceRegion-table if the region was used for maintenance.

I'm gonna try out different approaches and see what works best for us!  :)
