### ISSUE TITLE
Is RoadLayer table meant for road base course and sub layers?

### ISSUE THREAD

**Issue by Tapir79** [ORGTYTESPOO/kiradigiasm#8]

**Comment by ernogispo** [comment]
The idea is indeed that the RoadLayer table is meant for both road base course and sub layers. The earlier model was changed to based on first item "The first layer of the street is created when a new street is built" ("Kadun ensimmäinen päällystekerros syntyy kun uusi katu rakennetaan") in blog post https://kakedigi.wordpress.com/2017/06/07/omaisuudenhallinnan-tietomalli-kadun-kuntotieto-ja-paallysteet/.

**Comment by Tapir79** [comment]
Ok thanks! :)
