### ISSUE TITLE
Laws and regulations

### ISSUE THREAD

**Issue by ernogispo** [ORGTYTESPOO/kiradigiasm#9]
Laws and regulations should be considered in the model according to a Kakedigi blog post (https://kakedigi.wordpress.com/2017/07/06/omaisuudenhallinnan-tietosisallon-tyopajoja/). I wonder if the RoadMaintenanceRegion table, added in the latest model verision, is enough at this point.

**Comment by Tapir79** [comment]
I think this needs to be modelled in detail or at least we need to look into it. Anyway, all that was required in the Kiradigi -project is already done so this is "next version" stuff. I'm adding all ideas and enhancements as an issue-list here for the future.

**Comment by Tapir79** [comment]
One law we have in the model already (this we talked about in one of the workshops) and that's RoadMaintenanceDecision. It's the most important law concerning asset management and at this point I'm more than happy with your solution. Laws must be rewritten to each country anyway so in the Kiradigi -project, in my opinion, we could just point out that this should be considered. The Finnish law/regulation system could be included in next version. Do you agree?
